### ISSUE TITLE
BUG：1.6.5 doesn't seem to work anymore

### ISSUE THREAD

**Issue by jiajiala** [ohm-en/obsidian-plugin-manager#14]
I wonder if it can be repaired

**Comment by sergioatp** [comment]
I cant create dairly notes.
Here console errors>
app.js:1 TypeError: Cannot read properties of undefined (reading 'path')
    at w$ (app.js:1:2428627)
    at M$ (app.js:1:2429177)
    at Object.checkCallback (app.js:1:2461507)
    at app.js:1:2041658
    at Array.filter (<anonymous>)
    at e.listCommands (app.js:1:2041596)
    at e.getCommands (app.js:1:2628355)
    at t.getItems (app.js:1:2629398)
    at t.getSuggestions (app.js:1:1584598)
    at t.updateSuggestions (app.js:1:1583861)
(anonymous) @ app.js:1
e.listCommands @ app.js:1
e.getCommands @ app.js:1
t.getItems @ app.js:1
t.getSuggestions @ app.js:1
t.updateSuggestions @ app.js:1
t.onOpen @ app.js:1
t.onOpen @ app.js:1
e.open @ app.js:1
e.onOpen @ app.js:1
RK @ app.js:1
e.executeCommand @ app.js:1
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.handleKey @ app.js:1
t.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:journals:2174 Uncaught (in promise) TypeError: this.item.key.intersect is not a function
    at Node.intersect (plugin:journals:2174:30)
    at IntervalTree.tree_search_interval (plugin:journals:2653:22)
    at IntervalTree.search (plugin:journals:2341:14)
    at CalendarIndex.get (plugin:journals:2852:40)
    at CalendarJournalSection.getDatePath (plugin:journals:1923:44)
    at CalendarJournalSection.eval (plugin:journals:1863:35)
    at Generator.next (<anonymous>)
    at eval (plugin:journals:28:71)
    at new Promise (<anonymous>)
    at __awaiter (plugin:journals:24:12)
![2024-06-30 07_24_29-New tab - AIFusionVision - Obsidian v1 6 5](https://github.com/ohm-en/obsidian-plugin-manager/assets/20001097/d5a75ee9-1162-4fef-ae3c-9bfcbb93135d)

**Comment by ohm-en** [comment]
> I wonder if it can be repaired

I'll look into it when I get a chance. It would help if could provide any relevant information (are you running BRAT, does it work minimal plugins, what's the error, etc).



> I cant create dairly notes. Here console errors> app.js:1 TypeError: Cannot read properties of undefined (reading 'path') at w$ (app.js:1:2428627) at M$ (app.js:1:2429177) at Object.checkCallback (app.js:1:2461507) at app.js:1:2041658 at Array.filter () at e.listCommands (app.js:1:2041596) at e.getCommands (app.js:1:2628355) at t.getItems (app.js:1:2629398) at t.getSuggestions (app.js:1:1584598) at t.updateSuggestions (app.js:1:1583861) (anonymous) @ app.js:1 e.listCommands @ app.js:1 e.getCommands @ app.js:1 t.getItems @ app.js:1 t.getSuggestions @ app.js:1 t.updateSuggestions @ app.js:1 t.onOpen @ app.js:1 t.onOpen @ app.js:1 e.open @ app.js:1 e.onOpen @ app.js:1 RK @ app.js:1 e.executeCommand @ app.js:1 e.onTrigger @ app.js:1 e.handleKey @ app.js:1 e.handleKey @ app.js:1 t.handleKey @ app.js:1 e.onKeyEvent @ app.js:1 plugin:journals:2174 Uncaught (in promise) TypeError: this.item.key.intersect is not a function at Node.intersect (plugin:journals:2174:30) at IntervalTree.tree_search_interval (plugin:journals:2653:22) at IntervalTree.search (plugin:journals:2341:14) at CalendarIndex.get (plugin:journals:2852:40) at CalendarJournalSection.getDatePath (plugin:journals:1923:44) at CalendarJournalSection.eval (plugin:journals:1863:35) at Generator.next () at eval (plugin:journals:28:71) at new Promise () at __awaiter (plugin:journals:24:12) ![2024-06-30 07_24_29-New tab - AIFusionVision - Obsidian v1 6 5](https://private-user-images.githubusercontent.com/20001097/344449860-d5a75ee9-1162-4fef-ae3c-9bfcbb93135d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODYzNTYsIm5iZiI6MTcxOTc4NjA1NiwicGF0aCI6Ii8yMDAwMTA5Ny8zNDQ0NDk4NjAtZDVhNzVlZTktMTE2Mi00ZmVmLWFlM2MtOWJmY2JiOTMxMzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIyMjA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzA3Mzg2YjY0YTgwMzcwNzI4MzNjMjRjYmJmZjMxNzliOWFmMjFlZWRhYjQ5YjdlNjMwYWE0NDFlM2IxNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MkypethNZAiaOGo5wBCbfwaN_M24Kiec9tLX00nPAX4)

Please explain what you mean by daily note. Are you saying my plugin breaks the daily notes plugin?
